---
title: "Probability (2)"
subtitle: Data Analysis for Psychology in R 1
author: Tom Booth
---

```{r premable, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(kableExtra)
```

## Today
- Brief recap of probability rules
- Contingency tables and conditional probability
  - Our first test (without the actual test!)
- Introducing probability distributions

## Learning objectives
- Understand the use of probability rules to test dependence
- Understand broad concept of the probability distribution

## Rules of probability
1. For any event, $0 \leq p(A) \leq 1$
2. The sum of the probabilities of all possible outcomes = 1
3. $p(notA) = 1 - p(A)$ (probability of the complement)

## Rules of probability - union
4. For mutually exclusive events, $p(A \bigcup B) = p(A) + p(B)$ ($\bigcup$ = or)
5. General addition rule: $p(A \bigcup B) = p(A) + p(B) - p(A \bigcap B)$ ($\bigcap$ = and)
6. If A and B are independent, $p(A \bigcap B = p(A)p(B)$


## Conditional probability
- Rule 6 provides a way to assess if events are independent.

- When they are, we can talk of the **conditional probability** of events
- Probability of B **given** A, which is written, *p*(B|A)
- We can calculate conditional probability as;
- $p(B|A) = \frac{p(A \bigcap B)}{p(A)}$ 
  - Or: $p(A|B) = \frac{p(A \bigcap B)}{p(B)}$

## Conditional probability: an example (1)
- So let's consider an example:
- Consider a school with 100 students. There are 35 left handed students and 51 girls. Of those girls 10 are left handed. Now let's say we decide to limit the sample space to girls. What is the probability they are left handed?

## Conditional probability: an example (2)
- So the problem:
  - *p*(left handed **given** girl)
  - *p*(left handed $\bigcap$ girl) = $\frac{10}{100}$ = 0.10
  - *p*(girl) = $\frac{51}{100}$ = 0.51
  - *p*(left handed | girl) = $\frac{0.10}{0.51}$ = .196
- And note:
  - *p*(girl | left handed) = $\frac{0.10}{0.35}$ = .286

## Tabulating joint events (or first look at a statistic)
- So it is not quite our first look, and not quite a statistic (yet) but one way to think about joint probabilities is in a table.
- **Example**: Consider a different school with 100 pupils, 55 male and 45 female. Suppose we ask those students if they like stats. 40 say yes, 60 say no.

|          | Yes             | No            | Marginal |
|----------|-----------------|---------------|----------|
| Male     | p(Male, Yes)    | p(Male, No)   | 0.55     |
| Female   | p(Female & Yes) | p(Female, No) | 0.45     |
| Marginal | 0.40            | 0.60          | 1.00     |

## Tabulating joint events (or first look at a statistic)
- If we assume all events to be independent, then we know from the rules above the frequencies we would expect to see are the products of the two probabilities.

|          | Yes                | No                 | Marginal |
|----------|--------------------|--------------------|----------|
| Male     | $0.55*0.40 = 0.22$ | $0.55*0.60 = 0.33$ | 0.55     |
| Female   | $0.45*0.40 = 0.18$ | $0.45*0.60 = 0.27$ | 0.45     |
| Marginal | 0.40               | 0.60               | 1.00     |


## Tabulating joint events (or first look at a statistic)
- And this means that the probability of someone who says they like stats being male or female should be the same:
  - *p*(yes|male) = $\frac{.22}{.55}$ = 0.40
  - *p*(yes|female) = $\frac{.18}{.45}$ = 0.40

## Tabulating joint events (or first look at a statistic)
- But what if we observed;

|          | Yes  | No   | Marginal |
|----------|------|------|----------|
| Male     | 0.10 | 0.45 | 0.55     |
| Female   | 0.30 | 0.15 | 0.45     |
| Marginal | 0.40 | 0.60 | 1.00     |



## Tabulating joint events (or first look at a statistic)
- Given this, our conditional probabilities look like this;
  - $p(yes|male) = \frac{.10}{.55}$ = 0.18
  - $p(yes|female) = \frac{.30}{.45}$ = 0.67

- In other words, gender and whether you like stats are related.